jobs:
  - name: ami-id-update-mgmt-dev
    plan:
      - get: untested-al2-concourse-ami
        trigger: true
      - .: (( inject meta.plan.admin-activate-creds ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
      - .: (( inject meta.plan.update-ami-secrets ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
          inputs:
            - name: untested-al2-concourse-ami
      - .: (( inject meta.plan.workflow-dispatch ))
  - name: ami-id-update-mgmt
    plan:
      - get: dw-al2-concourse-ami
        trigger: false
      - .: (( inject meta.plan.update-ami-secrets ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-concourse-ami
