jobs:
- name: management
  plan:
  - get: aws-concourse
    passed:
    - management-dev
    trigger: true
  - get: packer-egress-test-release
  - .: (( inject meta.plan.terraform-bootstrap ))
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: management
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: management
  - .: (( inject meta.plan.terraform-output ))
    params:
      TF_WORKSPACE: management
  - .: (( inject meta.plan.concourse-smoke-tests ))
