jobs:
  - name: management-user-admin
    plan:
      - get: aws-concourse-users
        passed:
          - management-dev-user-admin
        trigger: true
      - .: (( inject meta.plan.create-users ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
      - .: (( inject meta.plan.delete-users ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
      - .: (( inject meta.plan.admin-reset-password ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
