jobs:
  - name: reboot-management-worker-nodes
    plan:
      - get: aws-concourse
        trigger: false
      - .: (( inject meta.plan.reboot-worker-nodes ))
        config:
          params:
            CONCOURSE_URI: "http://ci.local.dataworks.dwp.gov.uk:8080"
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
