jobs:
  - name: reboot-management-web-nodes
    plan:
      - get: aws-concourse
        trigger: false
      - .: (( inject meta.plan.reboot-web-nodes ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
