meta:
  plan:
   reboot-web-nodes:
      task: reboot-web-nodes
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_awscli_repository))
            version: ((dataworks.docker_awscli_version))
            tag: ((dataworks.docker_awscli_version))
        params:
          AWS_DEFAULT_REGION: ((dataworks.aws_region))
        run:
          path: sh
          args:
            - -exc
            - |
              source /assume-role
              for INSTANCE_ID in $(aws ec2 describe-instances --filters Name=tag:Name,Values=ci-concourse-web-* | jq -r '.Reservations[].Instances[].InstanceId');
              do
                aws autoscaling set-instance-health --instance-id $INSTANCE_ID --health-status Unhealthy
              done

   reboot-worker-nodes:
    task: reboot-worker-nodes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((dataworks.docker_awscli_repository))
          version: ((dataworks.docker_awscli_version))
          tag: ((dataworks.docker_awscli_version))
      params:
        AWS_DEFAULT_REGION: ((dataworks.aws_region))
        CONCOURSE_USERNAME: ((dataworks-secrets.concourse_user))
        CONCOURSE_PASSWORD: ((dataworks-secrets.concourse_password))
      run:
        path: sh
        args:
          - -exc
          - |
            source /assume-role
            curl -Lk -o fly.tgz "https://github.com/concourse/concourse/releases/download/v7.2.0/fly-7.2.0-linux-amd64.tgz"
            tar -xvf fly.tgz
            chmod +x fly
            ./fly --target concourse login --team-name main --concourse-url $CONCOURSE_URI -k -u $CONCOURSE_USERNAME -p $CONCOURSE_PASSWORD
            ./fly --target concourse workers
            for worker in $(./fly --target concourse workers  --json | jq -r .[].name);
            do
              ./fly --target concourse land-worker --worker $worker
            done

   admin-activate-creds:
      task: admin-activate-creds
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_awscli_repository))
            version: ((dataworks.docker_awscli_version))
            tag: ((dataworks.docker_awscli_version))
        params:
          AWS_DEFAULT_REGION: ((dataworks.aws_region))
          GHA_ACCESS_KEY_ID: ((dataworks-secrets.gha_aws_concourse_access_key_id))
        run:
          path: sh
          args:
            - -exc
            - |
              source /assume-role
              aws iam update-access-key --access-key-id $GHA_ACCESS_KEY_ID --status Active --user-name gha-aws-concourse
