name: "GHA Push Checks"
on:
  push:
    branches-ignore:
      - master
    paths:
      - ".github/workflows/**"
      - ".vscode/**"
defaults:
  run:
    working-directory: .github/workflows/

jobs:
  push:
    name: "On GHA Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible/ansible-lint-action@master
        with:
          files-to-validate: '[
          {
            "path": ".github/workflows/**",
            "schema": ".github/workflows/schema.json"
          }
        ]'
