name: "Push Checks"
on:
  push:
    branches-ignore:
      - master
    paths:
      - "terraform/**"
defaults:
  run:
    working-directory: terraform/

jobs:
  push:
    name: "On Terraform Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ terraform_13_version }}

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true
